version: '3.9'

services:
  # docker 容器启动的redis默认是没有redis.conf的配置文件，用docker启动redis之前，需要先去官网下载redis.conf的配置文件
  redis_db: # 服务名称
    image: daocloud.io/library/redis:6.0.3-alpine3.11
    container_name: nest-admin-redis
    restart: always
    # 配置redis.conf方式启动
    # command: redis-server /usr/local/etc/redis/redis.conf --requirepass 123456 --appendonly yes # 设置redis登录密码 123456、--appendonly yes：这个命令是用于开启redis数据持久化
    # 无需配置文件方式启动
    command: redis-server --appendonly yes # 开启redis数据持久化
    ports:
      - 6379:6379 # 本机端口:容器端口
    volumes:
      - ./docker-data/redis/db:/data # 把持久化数据挂载到宿主机
      - ./docker-data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf # 把redis的配置文件挂载到宿主机
      - ./docker-data/redis/logs:/logs # 用来存放日志
    environment:
      - TZ=Asia/Shanghai # 解决容器 时区的问题
    networks:
      - nest_admin_net

  mysql_db:
    image: daocloud.io/library/mysql:8.0.20
    container_name: nest-admin-mysql
    restart: always
    env_file:
      - .env
      #- .env.prod
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置utf8字符集
    volumes:
      - ./deploy/mysql/db:/var/lib/mysql # 用来存放了数据库表文件
      - ./deploy/mysql/conf/my.cnf:/etc/my.cnf # 存放自定义的配置文件
      # 我们在启动MySQL容器时自动创建我们需要的数据库和表
      # mysql官方镜像中提供了容器启动时自动docker-entrypoint-initdb.d下的脚本的功能
      - ./deploy/mysql/init:/docker-entrypoint-initdb.d/ # 存放初始化的脚本
    networks:
      - nest_admin_net

  nest-admin: # nestjs服务
    container_name: nest-admin
    build: # 根据Dockerfile构建镜像
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: pnpm run start:debug
    ports:
      - 3000:3000 # 本机端口:容器端口
    restart: on-failure # 设置自动重启，这一步必须设置，主要是存在mysql还没有启动完成就启动了node服务
    networks:
      - nest_admin_net
    depends_on: # node服务依赖于mysql和redis
      - redis_db
      - mysql_db

# 重要：将所有服务都挂载在同一网桥即可通过容器名来互相通信了
# 如nestjs连接mysql和redis，可以通过容器名来互相通信
networks:
  nest_admin_net:
    # 桥接?
    driver: bridge
